# Website settings
url: "https://jane-ite.github.io/"
baseurl: ""

# Internal nav
nav:
  main:
    projects: "/projects"
#    reading: "/reading"

# Bio settings
name: "Jane Liu"
description: "The home page of Jane Liu."
thumbnail_path: "profile-photos/.jpg"

# URLs
contact_urls:
  linkedin:
    url: ""
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: ""
    label: "GitHub"
    icon: "github-square"
  email:
    url: ""
    label: "Email"
    value: "liu.jane.ite@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
markdown: kramdown

disqus:
  shortname: donfung

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
