# Website settings
url: "https://jane-ite.github.io/"
baseurl: ""

# Internal nav
nav:
  main:
    projects: "/projects"
    dbfpage: "/dbfpage"

# Bio settings
name: "Jane Liu"
description: "The home page of Jane Liu."
thumbnail_path: "profile-photos/jane_sprucebruce.jpg"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/jane-liu-20b763180/"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/jane-ite/jane-ite.github.io"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:liu.jane.ite@gmail.com"
    label: "Email"
    value: "liu.jane.ite@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
markdown: kramdown

disqus:
  shortname: janeliu

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
